### ISSUE TITLE
with python 3.8 not work install requeriments.txt

### ISSUE THREAD

**Issue by johnfelipe** [aaronhuff/nft-name-generator#3]
```
root@ubuntu20portatil:~/nft-name-generator# pip install requirements.txt
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt
root@ubuntu20portatil:~/nft-name-generator# python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
root@ubuntu20portatil:~/nft-name-generator# cat requirements.txt
certifi==2022.6.15
charset-normalizer==2.1.0
idna==3.3
python-dotenv==0.20.0
PyYAML==6.0
requests==2.28.1
root@ubuntu20portatil:~/nft-name-generator# pip3 install requirements.txt
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt

```

**Comment by aaronhuff** [comment]
I think you need the -r switch.

> pip3 install -r requirements.txt

**Comment by johnfelipe** [comment]
working
next

```
root@ubuntu20portatil:~/nft-name-generator# python3 generator.py
Traceback (most recent call last):
  File "generator.py", line 41, in <module>
    class Main:
  File "generator.py", line 53, in Main
    animal_object_id = animal_db.randomAnimal()
  File "generator.py", line 15, in randomAnimal
    return(self.data['results'][animal_num]['objectId'])
KeyError: 'results'

```

**Comment by aaronhuff** [comment]
It's use the back4app utility to get the animal database. It uses ENV of BACKAPP_ID and BACKAPP_API_KEY to get the data. I will update the readme with details but you can get a free api key / account here [back4app](www.back4app.com/)

**Comment by johnfelipe** [comment]
ping me when is md file updated with all commands and instructions pls

**Comment by aaronhuff** [comment]
@johnfelipe It's been updated now. Maybe I should use a local copy of the db for ease of use etc but I was playing with back4app when I set this up. #4

**Comment by aaronhuff** [comment]
@johnfelipe I removed the back4app api call and just dumped the animal names into a yaml (like the adjectives were). Test it and let me know if has issues.

**Comment by johnfelipe** [comment]
Command for generate pls

**Comment by aaronhuff** [comment]
generator.Main() prints the result. If you want it to just return the string, I can create a class for that. You going to toss a webfront end?

**Comment by johnfelipe** [comment]
Yes I need web page deploy

**Comment by aaronhuff** [comment]
#6 I added a NFT class with a getName function that returns a string. So you should be able to put a frontend on that. Please do send me PR when done and I can add it the project. I'm not good with that stuff :)

**Comment by aaronhuff** [comment]
generator.NFT().getName() -> Returns project name string
